eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  application:
    name: microservicio-eureka-server
  cloud:
    config:
      uri: htpp://localhost:8888
      username: admin
      password: mipassword  