server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  cloud:
    config:
      uri: 
      - http://localhost:8888
      username: admin
      password: mipassword   