server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: microservicio-productos
        uri: lb://microservicio-productos
        predicates:
        - Path=/api/producto/**
      - id: microservicio-cesta
        uri: lb://microservicio-cesta
        predicates:
        - Path=/api/cesta/**